### ISSUE TITLE
无法运行/运行出错

### ISSUE THREAD

**Issue by oldyi** [xmoezzz/rfvp#4]
感谢作者的贡献！
我在自己的电脑上尝试构建了，但是没有正常运行。具体表现如下：

平台：windows10
尝试游戏：星辰恋曲FD
运行结果：产生窗口，白屏，没有声音。
弹出的控制台日志如下
> [log.txt](https://github.com/user-attachments/files/15928716/log.txt)完整
> 恕我不才这个东西在vscode的终端里显示时候没有乱码，但不知道为啥写入文件的时候它就有了

另外，由于本人的操作系统是win10，故将源码作以下改动：
> rfvp\src\subsystem\resources\text_manager.rs 1:
> ```rust
> use std::{fs, os::unix::fs::MetadataExt};
> ```
>  更改为
>  ```rust
> #[cfg(target_os = "unix")]
> use std::{fs, os::unix::fs::MetadataExt};
> 
> #[cfg(target_os = "windows")]
> use std::{fs, os::windows::fs::MetadataExt};
>  ```
> 以及rfvp\src\subsystem\resources\text_manager.rs 83：
> ```rust
> if meta_data.size() > 30 * 1024 * 1024 {
> ```
> 改为
> ```rust
> if meta_data.len() > 30 * 1024 * 1024 {
> ```

请问是我上述改动产生了错误影响，还是其实本项目并不支持Windows平台，亦或本项目处于开发阶段尚未完善？

不知道结尾怎么说总之先磕一个 orz

**Comment by oldyi** [comment]
啊顺带一提
我尝试在linux下构建
运行结果如下
 ```
ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
thread 'main' panicked at rfvp/src/app.rs:358:14:
Failed to create device: RequestDeviceError { inner: Core(LimitsExceeded(FailedLimit { name: "max_push_constant_size", requested: 256, allowed: 128 })) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
 遂将rfvp/src/app.rs:358:14处
`max_push_constant_size: 256`
改为
`max_push_constant_size: 128`
之后运行结果为：
没有出现窗口，没有声音，图标任务管理器出现图标
控制台间歇性输出
 `ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred`
运行日志如下
[log.txt](https://github.com/user-attachments/files/15929792/log.txt)依然是存在Konsole控制台中没有看见的乱码

系统环境为
> 操作系统： Debian GNU/Linux 12
> KDE Plasma 版本： 5.27.5
> KDE 程序框架版本： 5.103.0
> Qt 版本： 5.15.8
> 内核版本： 6.1.0-21-amd64 (64 位)
> 图形平台： Wayland
> 图形处理器： Mesa Intel® UHD Graphics 630
> 系统版本： Not Applicable

**Comment by oldyi** [comment]
啊顺带一提
我尝试在linux下构建
运行结果如下
```
ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred
thread 'main' panicked at rfvp/src/app.rs:358:14:
Failed to create device: RequestDeviceError { inner: Core(LimitsExceeded(FailedLimit { name: "max_push_constant_size", requested: 256, allowed: 128 })) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
遂将rfvp/src/app.rs:358:14处
`max_push_constant_size: 256`
改为
`max_push_constant_size: 128`

之后运行结果为：

没有出现窗口，没有声音，图标任务管理器出现图标
控制台间歇性输出
ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred

运行日志如下

> [log.txt](https://github.com/user-attachments/files/15929792/log.txt)依然是存在Konsole控制台中没有看见的乱码

系统环境为

>     操作系统： Debian GNU/Linux 12
>     KDE Plasma 版本： 5.27.5
>     KDE 程序框架版本： 5.103.0
>     Qt 版本： 5.15.8
>     内核版本： 6.1.0-21-amd64 (64 位)
>     图形平台： Wayland
>     图形处理器： Mesa Intel® UHD Graphics 630
>     系统版本： Not Applicable

手滑点错了不好意思

**Comment by xmoezzz** [comment]
依然在开发中，因为工作关系进度很缓慢
